export { default as Navbar } from './Navbar'
export { default as HeroSection } from './HeroSection'
export { default as Footer } from './Footer'
export { default as Main } from './Main'
export { default as Testimonial } from './Testimonial'